#trainer.py

#It was my first time working with this stuff 

#Trains a binary classifier (real=0 / ai=1) for each class from the labeled dataset
#generated by calibrator.py (output/features_<class>.csv).

#In the prototype I made just to test that things worked, each feature of the test image was compared to
#the mean of the REAL images via a Z-score. The resulting distances were weighted by manually defined weights
#and summed to produce a final score.

#That created a single-class anomaly-detection problem. Any image that was statistically distant from the
#distribution of real images tended to get a high "likely AI" score, including real images that had gone through
#heavy edits, HDR, scanning, aggressive denoising, or other processes that significantly alter their features.

#So I went with a supervised classifier that automatically learns the importance of each feature, handling
#correlated features better and producing more robust classifications.
#Random Forest is used as the default model, keeping logistic regression as an alternative.

import os
import json
import argparse
import numpy as np
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, confusion_matrix, classification_report,
)

OUTPUT_DIRECTORY = "output"


def loadDataset(classLabel: str) -> pd.DataFrame:
    path = os.path.join(OUTPUT_DIRECTORY, f"features_{classLabel}.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Dataset not found: {path}. Run calibrator.py first."
        )
    return pd.read_csv(path)


def buildModel(modelType: str):
    if modelType == "logistic":
        return Pipeline([
            ("scaler", StandardScaler()),
            ("clf", LogisticRegression(max_iter=2000, class_weight="balanced")),
        ])
    # default: random forest
    return RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )


def trainClass(classLabel: str, modelType: str = "random-forest", testProportion: float = 0.25):
    print(f"\nTraining classifier for: {classLabel} ")

    dataFrame = loadDataset(classLabel)

    if "label" not in dataFrame.columns:
        raise Exception(f"Dataset for '{classLabel}' has no 'label' column.")

    counts = dataFrame["label"].value_counts().to_dict()
    print(f"Samples -> real: {counts.get(0, 0)} | ai: {counts.get(1, 0)}")

    if counts.get(0, 0) < 10 or counts.get(1, 0) < 10:
        print(
            "WARNING: fewer than 10 samples in one of the classes. The training/evaluation "
            "result below is NOT statistically reliable - "
            "treat it as a pipeline smoke test, not real validation."
        )

    featureColumns = [columnName for columnName in dataFrame.columns if columnName not in ("label", "_file")]
    X = dataFrame[featureColumns].values
    y = dataFrame["label"].values

    XTrain, XTest, yTrain, yTest = train_test_split(
        X, y, test_size=testProportion, stratify=y, random_state=42
    )

    model = buildModel(modelType)
    model.fit(XTrain, yTrain)

    yPred = model.predict(XTest)
    yProba = model.predict_proba(XTest)[:, 1]

    metrics = {
        "accuracy": float(accuracy_score(yTest, yPred)),
        "precision": float(precision_score(yTest, yPred, zero_division=0)),
        "recall": float(recall_score(yTest, yPred, zero_division=0)),
        "f1": float(f1_score(yTest, yPred, zero_division=0)),
        "confusionMatrix": confusion_matrix(yTest, yPred).tolist(),
    }
    #AUC-ROC requires both classes to be present in the test set (in tests)
    if len(set(yTest)) == 2:
        metrics["rocAuc"] = float(roc_auc_score(yTest, yProba))

    print(json.dumps(metrics, indent=4))
    print(classification_report(yTest, yPred, target_names=["real", "ai"], zero_division=0))

    #cross-validation (more robust than a single split, useful for small datasets in tests)
    try:
        cvScores = cross_val_score(model, X, y, cv=5, scoring="roc_auc")
        print(f"AUC-ROC (5-fold CV): {cvScores.mean():.3f} +/- {cvScores.std():.3f}")
    except Exception as error:
        print(f"Cross-validation could not be run: {error}")

    #feature-importance (RandomForest) to keep forensic reasoning
    importances = None
    if hasattr(model, "feature_importances_"):
        importances = sorted(
            zip(featureColumns, model.feature_importances_.tolist()),
            key=lambda importancePair: importancePair[1], reverse=True,
        )
        print("\nMost relevant features for this class:")
        for name, value in importances[:10]:
            print(f"  {name}: {value:.4f}")

    #save model + metadata
    os.makedirs(OUTPUT_DIRECTORY, exist_ok=True)
    modelPath = os.path.join(OUTPUT_DIRECTORY, f"model_{classLabel}.joblib")
    joblib.dump({
        "model": model,
        "featureColumns": featureColumns,
        "modelType": modelType,
    }, modelPath)
    print(f"\nModel saved to: {modelPath}")

    metricsPath = os.path.join(OUTPUT_DIRECTORY, f"metrics_{classLabel}.json")
    with open(metricsPath, "w") as file:
        json.dump({
            "metrics": metrics,
            "featureImportances": importances,
        }, file, indent=4)
    print(f"Metrics saved to: {metricsPath}")


def main():
    parser = argparse.ArgumentParser(description="Trains the Jenos classifier by class.")
    parser.add_argument("--class", dest="classLabel", required=True, help="Class name (e.g.: faces, landscapes)")
    parser.add_argument("--model", default="random-forest", choices=["random-forest", "logistic"])
    parser.add_argument("--holdout", type=float, default=0.25)
    args = parser.parse_args()

    trainClass(args.classLabel, modelType=args.model, testProportion=args.holdout)


if __name__ == "__main__":
    main()
